## This is a basic workflow to help you get started with Actions
env:
  MABL_API_KEY: FYVkpZA1kuht82EoV4QMyQ
  # GITHUB_TOKEN:
  # WORKSPACE_ID: GGivzErOOyHHUKY5t10J6Q-w
  ENV_ID: mLDQAyprr1WXmcnqsvPAvw-e
  APP_ID: mUgiWjlxcDjWR91gljSKDw-a
  # TESTS_RUN_ID: VNTA4Ge3fogRJARtNloo1w-jr
  # DEPLOYMENT_EVENT_ID: iDjePKUbS2XYyDcZq5tmtA-v

on: [push]

name: mabl hello-world

jobs:
  test:
    name: mabl Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Functional test deployment
        id: mabl-test-deployment
        uses: mablhq/github-run-tests-action@v1
        env:
          # Use a "CI/CD Integration" type of mabl API key
          MABL_API_KEY: ${{ env.MABL_API_KEY }}
          # GITHUB_TOKEN: ${{ env.GITHUB_TOKEN }}
        with:
          application-id: ${{ env.APP_ID }}
          environment-id: ${{ env.ENV_ID }}
          # Runs for browsers
          browser-types: |
            chrome
          # Runs plans matching ANY of the following labels AND the environment/application IDs above
          plan-labels: |
            smoke
##
