# This is a basic workflow to help you get started with Actions
env:
  MABL_API_KEY: w324ZBubCsKWKXDpw2OBUQ
  # GITHUB_TOKEN:
  # WORKSPACE_ID: GGivzErOOyHHUKY5t10J6Q-w
  ENV_ID: mLDQAyprr1WXmcnqsvPAvw-e
  APP_ID: mUgiWjlxcDjWR91gljSKDw-a
  # TESTS_RUN_ID: VNTA4Ge3fogRJARtNloo1w-jr
  # DEPLOYMENT_EVENT_ID: iDjePKUbS2XYyDcZq5tmtA-v

on: [push]

name: mabl

jobs:
  test:
    name: Mabl Tests
    runs-on: windows-latest
    steps:
      - uses: actions/setup-node@v4
        with:
          node-version: '18.x'
      
      - uses: browser-actions/setup-chrome@v1
        with:
          chrome-version: 130

      - uses: mablhq/setup-mabl-cli@v1
        with:
          workspace-id: RPVhi2GsYAgwdADaIG1sQw-w
          application-id: ${{ env.APP_ID }}
          environment-id: ${{ env.ENV_ID }}
        env:
          MABL_API_KEY: ${{ env.MABL_API_KEY }}

      - name: Run check sandbox script
        run: mabl tests run --id bLsrFhxfczxGSeCqZux8jw-j --headless true
