# This is a basic workflow to help you get started with Actions
env:
  MABL_API_KEY: FYVkpZA1kuht82EoV4QMyQ
  # GITHUB_TOKEN:
  # WORKSPACE_ID: GGivzErOOyHHUKY5t10J6Q-w
  ENV_ID: mLDQAyprr1WXmcnqsvPAvw-e
  APP_ID: mUgiWjlxcDjWR91gljSKDw-a
  # TESTS_RUN_ID: VNTA4Ge3fogRJARtNloo1w-jr
  # DEPLOYMENT_EVENT_ID: iDjePKUbS2XYyDcZq5tmtA-v

on: [push]

name: mabl

jobs:
  test:
    name: Mabl Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-node@v4
        with:
          node-version: '18.x'

      - uses: mablhq/setup-mabl-cli@v1
        with:
          application-id: ${{ env.APP_ID }}
          environment-id: ${{ env.ENV_ID }}
        env:
          MABL_API_KEY: ${{ env.MABL_API_KEY }}

      - name: Run check sandbox script
        run: mabl auth activate-key ${{ env.MABL_API_KEY }} && mabl tests run --id bLsrFhxfczxGSeCqZux8jw-j --headless true --environment-id mLDQAyprr1WXmcnqsvPAvw-e 
